server:
  port: 8085

spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
                allowedOrigins: "http://localhost:3000"
                allowedMethods: "*"
                allowedHeaders: "*"

      routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
        - Path=/employees/**
        filters:
        - AuthFilter
        
      - id: LEAVE-SERVICE
        uri: lb://LEAVE-SERVICE
        predicates:
        - Path=/leaves/**
        
      - id: MANAGER-SERVICE
        uri: lb://MANAGER-SERVICE
        predicates:
        - Path=/managers/**
        filters:
        - AuthFilter
        
      - id: TASK-SERVICE
        uri: lb://TASK-SERVICE
        predicates:
        - Path=/tasks/**
        
      - id: ADMIN-SERVICE
        uri: lb://ADMIN-SERVICE
        predicates:
        - Path=/admin/**
        filters:
        - AuthFilter
        
      - id: LOGIN-SERVICE
        uri: lb://LOGIN-SERVICE
        predicates:
        - Path=/auth/**
          


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
      
      
      
      
      






